version: "3.8"
services:
  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    # network_mode: "host"
    environment:
      - VITE_SERVER_DATA=http://backend:3000
    depends_on:
      - backend
  backend:
    build:
      context: ../P12-NodeJs-backend
    ports:
      - "3000:3000"