version: '3.8'
services:
  frontend-prod: &frontend
    build:
      context: .
    profiles: ['prod']
    ports:
      - '5173:5173'
    # env_file: .env
    environment:
      APP_ENV: prod
    depends_on:
      - server-backend
    volumes:
      - .:/app

  frontend-dev:
    # <<: *frontend
    build:
      context: .
    profiles: ['dev']
    environment:
      APP_ENV: dev
    # depends_on:
    #   - mocked-backend
    ports:
      - '5173:5173'
      - '4001:4001'
    volumes:
      - .:/app

  server-backend:
    build:
      context: ../P12-NodeJs-backend
    profiles: ['prod']
    volumes:
      - ../P12-NodeJs-backend:/app
    ports:
      - '3000:3000'

  # mocked-backend:
  #   build:
  #     context: .
  #   profiles: ['dev']
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '4001:4001'